version: "3.8"

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres-docker
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_postgres:/documents/cursos/BLUE/modulo-05-blue
    ports:
      - 5432:5432
    expose:
      - 5432
  prisma:
    container_name: prisma-docker
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_SERVER_PORT}
        database:
          default:
            host: ${DATABASE_HOST}
            port: ${DATABASE_PORT}
            user: ${DATABASE_USER}
            password: ${DATABASE_PASSWORD}

volumes:
  db_postgres:
